name: Generate PDF

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc + TeX Live
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended \
                                   texlive-extra-utils texlive-latex-extra texlive-xetex

      - name: Build guide.pdf
        run: |
          : > combined.md   # truncate/create
          for i in {1..5}; do
            for md in ${i}-*.md; do
              [ -e "$md" ] || continue
              echo "Adding $md"
              cat "$md" >> combined.md
              printf "\n\n" >> combined.md
            done
          done

          pandoc combined.md \
            -o guide.pdf \
            --pdf-engine=xelatex \
            -V geometry:margin=1in \
            -V mainfont="DejaVu Sans" \
            -V monofont="DejaVu Sans Mono"

      - name: Commit & push PDF
        run: |
          git config --global user.name  'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
          # 1 – stage the newly‑generated / updated file
          git add guide.pdf
      
          # 2 – bring main up‑to‑date and replay our staged changes if needed
          git pull --rebase --autostash --quiet
      
          # 3 – record a commit only when the PDF actually changed
          git commit -m "Update PDF guide [skip ci]" || echo "Nothing new"
      
          git push --quiet

